baseURL = "http://example.org/"
languageCode = "en-us"
title = "Highlander's Heart"
theme = "hlheart"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true

